name: Rust CI

on:
  push:
    branches: [ "cargo" ]
  pull_request:
    branches: [ "cargo" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    defaults:
      run:
        working-directory: lode-rs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
      with:
        components: rustfmt, clippy

    - name: Install tools
      run: cargo install --locked cargo-nextest

    - name: Run rustfmt
      run: cargo fmt --check

    - name: Run clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo nextest run --workspace

  security:
    defaults:
      run:
        working-directory: lode-rs
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.17.0

      - name: Install tools
        run: |
          cargo install cargo-deny
          cargo install cargo-audit

      - name: Run deny
        if: always()
        run: cargo deny --locked check

      - name: Run audit
        if: always()
        run: cargo audit --locked

      - name: Generate SARIF reports
        if: always()
        run: |
          mkdir sarif-output
          cargo deny --format sarif check > sarif-output/deny-report.sarif || true
          cargo audit --format sarif > sarif-output/audit-report.sarif || true

      - name: Upload SARIF reports
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: lode-rs/sarif-output
